# Generated by Django 5.2.4 on 2026-02-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_benefits_product_features_product_is_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
