"""
Django settings for Rukkie project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from dotenv import load_dotenv, dotenv_values
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local .env if present
load_dotenv(BASE_DIR / '.env')
DOTENV_FALLBACK = dotenv_values(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment; in production (DEBUG=False) it is required.
SECRET_KEY = os.environ.get('SECRET_KEY')

# Production settings (override with env in development)
# Accept common truthy values for DEBUG; default to True for local dev.
DEBUG = str(os.environ.get('DEBUG', 'True')).strip().lower() in ('1', 'true', 'yes', 'on')

# Ensure a secret key is provided in non-debug (production) mode
if not DEBUG and not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY environment variable is required when DEBUG=False')

# Accept Render domains and local hosts; allow override via env var
if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
else:
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '.onrender.com').split(',') if h.strip()]

# Media backend toggle.
# Set USE_CLOUDINARY_MEDIA=True in production to store uploads in Cloudinary.
USE_CLOUDINARY_MEDIA = str(os.environ.get('USE_CLOUDINARY_MEDIA', 'False')).strip().lower() in ('1', 'true', 'yes', 'on')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Project apps and third-party
INSTALLED_APPS += [
    'corsheaders',
    'rest_framework',
    'store',
]
if USE_CLOUDINARY_MEDIA:
    INSTALLED_APPS += [
        'cloudinary_storage',
        'cloudinary',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'Rukkie.request_hardening.RequestHardeningMiddleware',
    'Rukkie.security_headers.SecurityHeadersMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'Rukkie.middleware.CSPMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Rukkie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Rukkie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    # Local development: use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Production: expect a DATABASE_URL env var (Postgres)
    DATABASE_URL = os.environ.get('DATABASE_URL')
    if not DATABASE_URL:
        raise ImproperlyConfigured('DATABASE_URL environment variable is required when DEBUG=False')
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Where `collectstatic` will place files for WhiteNoise / serving
STATIC_ROOT = BASE_DIR / 'static'

# Where the frontend build will output assets during CI/build.
# Point to the `build` directory so `assets/` is served at `/static/assets/...`.
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'build',
]

# Do NOT include STATIC_ROOT in STATICFILES_DIRS (Django error E002).
# Keep only the frontend build assets here; collected/static files go to STATIC_ROOT.

# Use WhiteNoise compressed manifest storage for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media (user-uploaded) files
MEDIA_ROOT = BASE_DIR / 'media'
if USE_CLOUDINARY_MEDIA:
    # Prefer CLOUDINARY_URL (cloudinary://<api_key>:<api_secret>@<cloud_name>)
    # and fall back to explicit CLOUDINARY_* variables.
    cloudinary_url = (os.environ.get('CLOUDINARY_URL') or '').strip()
    cloudinary_cloud_name = ''
    cloudinary_api_key = ''
    cloudinary_api_secret = ''
    if cloudinary_url:
        try:
            parsed = urlparse(cloudinary_url)
            if parsed.scheme == 'cloudinary':
                cloudinary_cloud_name = (parsed.hostname or '').strip()
                cloudinary_api_key = (parsed.username or '').strip()
                cloudinary_api_secret = (parsed.password or '').strip()
        except Exception:
            cloudinary_cloud_name = ''
            cloudinary_api_key = ''
            cloudinary_api_secret = ''
    if not cloudinary_cloud_name:
        cloudinary_cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME', '').strip()
    if not cloudinary_api_key:
        cloudinary_api_key = os.environ.get('CLOUDINARY_API_KEY', '').strip()
    if not cloudinary_api_secret:
        cloudinary_api_secret = os.environ.get('CLOUDINARY_API_SECRET', '').strip()
    if not (cloudinary_cloud_name and cloudinary_api_key and cloudinary_api_secret) and not DEBUG:
        raise ImproperlyConfigured(
            'Cloudinary media is enabled but credentials are missing. '
            'Set CLOUDINARY_URL or CLOUDINARY_CLOUD_NAME/CLOUDINARY_API_KEY/CLOUDINARY_API_SECRET.'
        )

    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': cloudinary_cloud_name,
        'API_KEY': cloudinary_api_key,
        'API_SECRET': cloudinary_api_secret,
        'SECURE': str(os.environ.get('CLOUDINARY_SECURE', 'True')).strip().lower() in ('1', 'true', 'yes', 'on'),
    }
    MEDIA_URL = f"https://res.cloudinary.com/{cloudinary_cloud_name}/" if cloudinary_cloud_name else '/media/'
    STORAGES = {
        'default': {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }
else:
    MEDIA_URL = '/media/'
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security headers and CSP
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://*.onrender.com').split(',')

# Only apply strict security settings when not in DEBUG (production).
# In development we keep these off so the runserver works over HTTP.
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
else:
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_PROXY_SSL_HEADER = None
    USE_X_FORWARDED_HOST = False
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'unsafe-none'

X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True

# Content Security Policy value is injected by middleware

# CORS settings: allow localhost and frontend origins during development and
# rely on environment variables / production settings when DEBUG is False.
CORS_ALLOW_CREDENTIALS = True
if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ]
else:
    # In production, set exact allowed origins via env var.
    # Wildcard patterns should be configured in CORS_ALLOWED_ORIGIN_REGEXES.
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
        if o.strip() and '*' not in o
    ]

# Allow regex for local dev and render wildcard
CORS_ALLOWED_ORIGIN_REGEXES = [r"^https?://localhost(:\d+)?$", r"^https?://127\.0\.0\.1(:\d+)?$", r"^https?://.*\.onrender\.com$"]

# Additional security header settings
# Permissions-Policy header value (optional override via env)
PERMISSIONS_POLICY = os.environ.get('PERMISSIONS_POLICY', "geolocation=(), microphone=(), camera=()")

# Referrer policy
REFERRER_POLICY = os.environ.get('REFERRER_POLICY', 'same-origin')

# Email settings
def _env_bool(name: str, default: bool = False) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return str(val).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_int(name: str, default: int) -> int:
    val = os.environ.get(name)
    if val is None:
        return default
    try:
        return int(str(val).strip())
    except Exception:
        return default


def _env_first(*names: str, default: str = '') -> str:
    for name in names:
        val = os.environ.get(name)
        if val is not None and str(val).strip():
            return str(val).strip()
        # If host env var is missing/blank, fall back to non-empty .env value.
        file_val = DOTENV_FALLBACK.get(name)
        if file_val is not None and str(file_val).strip():
            return str(file_val).strip()
    return default


EMAIL_USE_CONSOLE = _env_bool('EMAIL_USE_CONSOLE', DEBUG)
EMAIL_BACKEND = (
    os.environ.get('EMAIL_BACKEND', '').strip()
    or ('django.core.mail.backends.console.EmailBackend' if EMAIL_USE_CONSOLE else 'django.core.mail.backends.smtp.EmailBackend')
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '').strip()
EMAIL_PORT = _env_int('EMAIL_PORT', 587)
EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', False)
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', not EMAIL_USE_SSL)
if EMAIL_USE_SSL and EMAIL_USE_TLS:
    # TLS and SSL are mutually exclusive in Django's email backend.
    EMAIL_USE_TLS = False
EMAIL_TIMEOUT = _env_int('EMAIL_TIMEOUT', 10)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', '').strip() or EMAIL_HOST_USER or 'no-reply@derukkies.com'
CONTACT_RECIPIENT_EMAIL = os.environ.get('CONTACT_RECIPIENT_EMAIL', DEFAULT_FROM_EMAIL)

# Payment provider secrets (set via environment in Render)
STRIPE_SECRET_KEY = _env_first(
    'STRIPE_SECRET_KEY',
    'STRIPE_API_KEY',
)
STRIPE_PUBLISHABLE_KEY = _env_first(
    'STRIPE_PUBLISHABLE_KEY',
    'STRIPE_PUBLIC_KEY',
)
STRIPE_MODE = _env_first(
    'STRIPE_MODE',
    default=('LIVE' if not DEBUG else 'TEST'),
).strip().upper()
FLUTTERWAVE_SECRET_KEY  = _env_first(
    'FLUTTERWAVE_SECRET_KEY',
    'FLW_SECRET_KEY',
    'FLW_SECRET',
    'FLUTTERWAVE_SECRET',
    'RAVE_SECRET_KEY',
)
FLUTTERWAVE_PUBLIC_KEY = _env_first(
    'FLUTTERWAVE_PUBLIC_KEY',
    'FLW_PUBLIC_KEY',
)
FLUTTERWAVE_ENCRYPTION_KEY = _env_first(
    'FLUTTERWAVE_ENCRYPTION_KEY',
    'FLW_ENCRYPTION_KEY',
)
FLUTTERWAVE_BASE_URL = _env_first(
    'FLUTTERWAVE_BASE_URL',
    default='https://api.flutterwave.com/v3',
).rstrip('/')
FLUTTERWAVE_MODE = _env_first(
    'FLUTTERWAVE_MODE',
    default=('LIVE' if not DEBUG else 'TEST'),
).strip().upper()
PAYPAL_CLIENT_ID = _env_first(
    'PAYPAL_CLIENT_ID',
)
PAYPAL_CLIENT_SECRET = _env_first(
    'PAYPAL_CLIENT_SECRET',
    'PAYPAL_SECRET',
)
# Backward compatibility with existing code paths that still read PAYPAL_SECRET.
PAYPAL_SECRET = PAYPAL_CLIENT_SECRET
PAYPAL_ENV = _env_first(
    'PAYPAL_ENV',
    'PAYPAL_MODE',
    default=('live' if not DEBUG else 'sandbox'),
).strip().lower()
# Backward compatibility with existing code paths that still read PAYPAL_MODE.
PAYPAL_MODE = PAYPAL_ENV
# Webhook / verification secrets
STRIPE_WEBHOOK_SECRET = _env_first(
    'STRIPE_WEBHOOK_SECRET',
    'STRIPE_ENDPOINT_SECRET',
)
FLUTTERWAVE_WEBHOOK_SECRET = _env_first(
    'FLUTTERWAVE_WEBHOOK_SECRET',
    'FLUTTERWAVE_SECRET_HASH',
    'FLW_SECRET_HASH',
)
PAYPAL_WEBHOOK_ID = os.environ.get('PAYPAL_WEBHOOK_ID', '')
# Optional generic verification token for internal endpoints
PAYMENT_VERIFY_TOKEN = os.environ.get('PAYMENT_VERIFY_TOKEN', '')

# Checkout pricing defaults (server-authoritative)
CHECKOUT_FREE_SHIPPING_THRESHOLD = float(os.environ.get('CHECKOUT_FREE_SHIPPING_THRESHOLD', '100'))
CHECKOUT_FLAT_SHIPPING = float(os.environ.get('CHECKOUT_FLAT_SHIPPING', '9.99'))
CHECKOUT_TAX_RATE = float(os.environ.get('CHECKOUT_TAX_RATE', '0.08'))

# Request/upload limits.
# Keep a conservative global body limit, but allow larger admin CSV+ZIP imports.
REQUEST_BODY_MAX_BYTES = _env_int('REQUEST_BODY_MAX_BYTES', 2 * 1024 * 1024)
CSV_IMPORT_MAX_BYTES = _env_int('CSV_IMPORT_MAX_BYTES', 200 * 1024 * 1024)
FILE_UPLOAD_MAX_MEMORY_SIZE = _env_int('FILE_UPLOAD_MAX_MEMORY_SIZE', 10 * 1024 * 1024)
DATA_UPLOAD_MAX_MEMORY_SIZE = max(REQUEST_BODY_MAX_BYTES, CSV_IMPORT_MAX_BYTES)

# API rate limits (requests per window, keyed by client IP and optional identifier)
RATE_LIMIT_CHAT_LIMIT = _env_int('RATE_LIMIT_CHAT_LIMIT', 45)
RATE_LIMIT_CHAT_WINDOW_SECONDS = _env_int('RATE_LIMIT_CHAT_WINDOW_SECONDS', 60)
RATE_LIMIT_CONTACT_LIMIT = _env_int('RATE_LIMIT_CONTACT_LIMIT', 8)
RATE_LIMIT_CONTACT_WINDOW_SECONDS = _env_int('RATE_LIMIT_CONTACT_WINDOW_SECONDS', 300)
RATE_LIMIT_NEWSLETTER_LIMIT = _env_int('RATE_LIMIT_NEWSLETTER_LIMIT', 10)
RATE_LIMIT_NEWSLETTER_WINDOW_SECONDS = _env_int('RATE_LIMIT_NEWSLETTER_WINDOW_SECONDS', 300)
RATE_LIMIT_AUTH_REGISTER_LIMIT = _env_int('RATE_LIMIT_AUTH_REGISTER_LIMIT', 8)
RATE_LIMIT_AUTH_REGISTER_WINDOW_SECONDS = _env_int('RATE_LIMIT_AUTH_REGISTER_WINDOW_SECONDS', 600)
RATE_LIMIT_AUTH_LOGIN_LIMIT = _env_int('RATE_LIMIT_AUTH_LOGIN_LIMIT', 12)
RATE_LIMIT_AUTH_LOGIN_WINDOW_SECONDS = _env_int('RATE_LIMIT_AUTH_LOGIN_WINDOW_SECONDS', 300)
RATE_LIMIT_PAYPAL_CREATE_ORDER_LIMIT = _env_int('RATE_LIMIT_PAYPAL_CREATE_ORDER_LIMIT', 40)
RATE_LIMIT_PAYPAL_CREATE_ORDER_WINDOW_SECONDS = _env_int('RATE_LIMIT_PAYPAL_CREATE_ORDER_WINDOW_SECONDS', 60)
RATE_LIMIT_PAYPAL_CAPTURE_ORDER_LIMIT = _env_int('RATE_LIMIT_PAYPAL_CAPTURE_ORDER_LIMIT', 40)
RATE_LIMIT_PAYPAL_CAPTURE_ORDER_WINDOW_SECONDS = _env_int('RATE_LIMIT_PAYPAL_CAPTURE_ORDER_WINDOW_SECONDS', 60)
RATE_LIMIT_PAYPAL_WEBHOOK_LIMIT = _env_int('RATE_LIMIT_PAYPAL_WEBHOOK_LIMIT', 180)
RATE_LIMIT_PAYPAL_WEBHOOK_WINDOW_SECONDS = _env_int('RATE_LIMIT_PAYPAL_WEBHOOK_WINDOW_SECONDS', 60)

LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').upper()

# Django REST Framework defaults
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

# Celery / background task settings
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)

# Image metadata auto-apply confidence threshold (0.0 - 1.0)
STORE_AUTO_APPLY_CONFIDENCE = float(os.environ.get('STORE_AUTO_APPLY_CONFIDENCE', '0.85'))
# Run metadata analysis asynchronously via Celery when True.
# Default: synchronous in DEBUG for immediate admin feedback.
STORE_METADATA_ASYNC = _env_bool('STORE_METADATA_ASYNC', not DEBUG)
# Toggle use of external vision API (optional)
STORE_USE_EXTERNAL_VISION = _env_bool('STORE_USE_EXTERNAL_VISION', False)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s | %(levelname)s | %(name)s | %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'store': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
